# Generated by Django 4.0.1 on 2023-03-27 11:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeorDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/')),
                ('dislike', models.ManyToManyField(related_name='fordislike', to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(related_name='forlike', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
